FROM jupyter/scipy-notebook:6c3390a9292e
RUN pip install --pre jupyterhub==1.0.0

# RUN pip install jupyterhub==1.0.0

# RUN conda install --quiet --yes \
#     'r-base=3.4.1' \
#     'r-irkernel=0.8*'&& \
#     conda clean -tipsy
